---

hadoop_cfg_path: "/opt/hadoop/etc/hadoop"
hadoop_user: cc
hadoop_group: cc

clear_configs: []

core_site: {}

core_site_name:
  fs.defaultFS

core_site_value:
  "{{ hostvars[groups['hadoop-master'][0]].ansible_hostname }}"

hdfs_site: {}

yarn_site: {}

yarn_site_name: 
  yarn.resourcemanager.hostname
yarn_site_value:
  "{{ hostvars[groups['hadoop-master'][0]].ansible_hostname }}"

mapred_site: {}

mapred_site_name:
  mapreduce.framework.name
mapred_site_value:
  yarn

