---

#- name: install maven
#  hosts: master0
#  remote_user: cc
#  roles:
#   - role: maven

- name: add data to hadoop dfs, compile, test
  hosts: master0
  become: yes
  become_user: hadoop
  vars:
     local_home: "{{ lookup('env','HOME') }}"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
  roles:
   - role: asl
